### Criar um novo usuário ###
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Antonio Ribeiro",
  "email": "antonioribeiroamg@gmail.com",
  "password": "123456"
}

### Validate User ###
GET http://localhost:3000/auth/verification-token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFudG9uaW9yaWJlaXJvYW1nQGdtYWlsLmNvbSIsImlhdCI6MTcxMjcxMzUyNSwiZXhwIjoxNzEyNzk5OTI1fQ.QaKUD2TRGasPlIVmrShBKEgG-tPxQeyvhLYb1MmU598

### Listar todos os usuários ###
GET http://localhost:3000/users

### Buscar um usuário por ID ###
GET http://localhost:3000/users/cluneyvke0000kdqsqe0czfpl

### Atualizar um usuário por ID ###
PATCH http://localhost:3000/users/cluneyvke0000kdqsqe0czfpl
Content-Type: application/json

{
  "name": "Antonio"
}

### Deletar um usuário por ID ###
DELETE http://localhost:3000/users/2ebecf31-6299-4e78-a565-466326503460

### Fazer Login ###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "antonioribeiroamg@gmail.com",
  "password": "123456"
}

### Return User With Token ###
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZTZmZDZlNC1hOGQyLTQwNjktYTRiMy1hYTIyMjdhMTM1NTMiLCJuYW1lIjoiQW50b25pbyBSaWJlaXJvIiwiZW1haWwiOiJhbnRvbmlvcmliZWlyb2FtZ0BnbWFpbC5jb20iLCJlbWFpbFZlcmlmaWVkIjoiMjAyNC0wNC0xMFQxNjozNzo0Ny42NDVaIiwiaW1hZ2UiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NMbmpjbThjclNxc2wzOHFNODNVRFFBdkZfRmZBdFMyOThmM1NkZDFXRzY3NWp0dThxcT1zOTYtYyIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzEyNzk0MDk4LCJleHAiOjE3MTI4ODA0OTh9.olOQZJfwSoM7sDDn9cPqlDq43G5EWoCdETfs_wBMyYw

### Fazer Login Google ###
GET http://localhost:3000/auth/google/login

### Fazer Logout ###
GET http://localhost:3000/auth/logout
